### ISSUE TITLE
Global security context not applied to job 

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/k8s-metadata-injection#201]
Currently the pod security context is not applied to the pod's job.

```
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
```

I believe that it was a decision taken at some point, but in some environments makes more difficult to run pods
